#############################################################################
# Makefile for building: Openni2
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Feb 26 18:17:12 2014
# Project:  Openni2.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Openni2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../OpenNI/Include -I/usr/include/pcl-1.7 -I/usr/include/eigen3 -I/usr/include/vtk-5.8 -I/usr/include/boost -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/home/cv-group/QT/Openni2 -lOpenNI2 -lopencv_highgui -lopencv_core -lopencv_imgproc -L/usr/lib/ -lpcl_common -lpcl_filters -lpcl_io -lpcl_visualization -lboost_system -lboost_thread -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		viewer.cpp \
		viewer_error.cpp \
		viewer_visualizer.cpp \
		viewer_keyio.cpp \
		viewer_pcl.cpp \
		viewer_save.cpp \
		sliders.cpp moc_sliders.cpp
OBJECTS       = main.o \
		viewer.o \
		viewer_error.o \
		viewer_visualizer.o \
		viewer_keyio.o \
		viewer_pcl.o \
		viewer_save.o \
		sliders.o \
		moc_sliders.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Openni2.pro
QMAKE_TARGET  = Openni2
DESTDIR       = 
TARGET        = Openni2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_sliders.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Openni2.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Openni2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Openni2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Openni21.0.0 || $(MKDIR) .tmp/Openni21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Openni21.0.0/ && $(COPY_FILE) --parents viewer.h sliders.h .tmp/Openni21.0.0/ && $(COPY_FILE) --parents main.cpp viewer.cpp viewer_error.cpp viewer_visualizer.cpp viewer_keyio.cpp viewer_pcl.cpp viewer_save.cpp sliders.cpp .tmp/Openni21.0.0/ && $(COPY_FILE) --parents sliders.ui .tmp/Openni21.0.0/ && (cd `dirname .tmp/Openni21.0.0` && $(TAR) Openni21.0.0.tar Openni21.0.0 && $(COMPRESS) Openni21.0.0.tar) && $(MOVE) `dirname .tmp/Openni21.0.0`/Openni21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Openni21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_sliders.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_sliders.cpp
moc_sliders.cpp: sliders.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sliders.h -o moc_sliders.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_sliders.h
compiler_uic_clean:
	-$(DEL_FILE) ui_sliders.h
ui_sliders.h: sliders.ui
	/usr/bin/uic-qt4 sliders.ui -o ui_sliders.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp viewer.h \
		../../OpenNI/Include/OpenNI.h \
		../../OpenNI/Include/OniPlatform.h \
		../../OpenNI/Include/Win32/OniPlatformWin32.h \
		../../OpenNI/Include/Android-Arm/OniPlatformAndroid-Arm.h \
		../../OpenNI/Include/Linux-x86/OniPlatformLinux-x86.h \
		../../OpenNI/Include/Linux-Arm/OniPlatformLinux-Arm.h \
		../../OpenNI/Include/MacOSX/OniPlatformMacOSX.h \
		../../OpenNI/Include/OniProperties.h \
		../../OpenNI/Include/OniEnums.h \
		../../OpenNI/Include/OniCAPI.h \
		../../OpenNI/Include/OniCTypes.h \
		../../OpenNI/Include/OniCEnums.h \
		../../OpenNI/Include/OniCProperties.h \
		../../OpenNI/Include/OniVersion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

viewer.o: viewer.cpp viewer.h \
		../../OpenNI/Include/OpenNI.h \
		../../OpenNI/Include/OniPlatform.h \
		../../OpenNI/Include/Win32/OniPlatformWin32.h \
		../../OpenNI/Include/Android-Arm/OniPlatformAndroid-Arm.h \
		../../OpenNI/Include/Linux-x86/OniPlatformLinux-x86.h \
		../../OpenNI/Include/Linux-Arm/OniPlatformLinux-Arm.h \
		../../OpenNI/Include/MacOSX/OniPlatformMacOSX.h \
		../../OpenNI/Include/OniProperties.h \
		../../OpenNI/Include/OniEnums.h \
		../../OpenNI/Include/OniCAPI.h \
		../../OpenNI/Include/OniCTypes.h \
		../../OpenNI/Include/OniCEnums.h \
		../../OpenNI/Include/OniCProperties.h \
		../../OpenNI/Include/OniVersion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewer.o viewer.cpp

viewer_error.o: viewer_error.cpp viewer.h \
		../../OpenNI/Include/OpenNI.h \
		../../OpenNI/Include/OniPlatform.h \
		../../OpenNI/Include/Win32/OniPlatformWin32.h \
		../../OpenNI/Include/Android-Arm/OniPlatformAndroid-Arm.h \
		../../OpenNI/Include/Linux-x86/OniPlatformLinux-x86.h \
		../../OpenNI/Include/Linux-Arm/OniPlatformLinux-Arm.h \
		../../OpenNI/Include/MacOSX/OniPlatformMacOSX.h \
		../../OpenNI/Include/OniProperties.h \
		../../OpenNI/Include/OniEnums.h \
		../../OpenNI/Include/OniCAPI.h \
		../../OpenNI/Include/OniCTypes.h \
		../../OpenNI/Include/OniCEnums.h \
		../../OpenNI/Include/OniCProperties.h \
		../../OpenNI/Include/OniVersion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewer_error.o viewer_error.cpp

viewer_visualizer.o: viewer_visualizer.cpp viewer.h \
		../../OpenNI/Include/OpenNI.h \
		../../OpenNI/Include/OniPlatform.h \
		../../OpenNI/Include/Win32/OniPlatformWin32.h \
		../../OpenNI/Include/Android-Arm/OniPlatformAndroid-Arm.h \
		../../OpenNI/Include/Linux-x86/OniPlatformLinux-x86.h \
		../../OpenNI/Include/Linux-Arm/OniPlatformLinux-Arm.h \
		../../OpenNI/Include/MacOSX/OniPlatformMacOSX.h \
		../../OpenNI/Include/OniProperties.h \
		../../OpenNI/Include/OniEnums.h \
		../../OpenNI/Include/OniCAPI.h \
		../../OpenNI/Include/OniCTypes.h \
		../../OpenNI/Include/OniCEnums.h \
		../../OpenNI/Include/OniCProperties.h \
		../../OpenNI/Include/OniVersion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewer_visualizer.o viewer_visualizer.cpp

viewer_keyio.o: viewer_keyio.cpp viewer.h \
		../../OpenNI/Include/OpenNI.h \
		../../OpenNI/Include/OniPlatform.h \
		../../OpenNI/Include/Win32/OniPlatformWin32.h \
		../../OpenNI/Include/Android-Arm/OniPlatformAndroid-Arm.h \
		../../OpenNI/Include/Linux-x86/OniPlatformLinux-x86.h \
		../../OpenNI/Include/Linux-Arm/OniPlatformLinux-Arm.h \
		../../OpenNI/Include/MacOSX/OniPlatformMacOSX.h \
		../../OpenNI/Include/OniProperties.h \
		../../OpenNI/Include/OniEnums.h \
		../../OpenNI/Include/OniCAPI.h \
		../../OpenNI/Include/OniCTypes.h \
		../../OpenNI/Include/OniCEnums.h \
		../../OpenNI/Include/OniCProperties.h \
		../../OpenNI/Include/OniVersion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewer_keyio.o viewer_keyio.cpp

viewer_pcl.o: viewer_pcl.cpp viewer.h \
		../../OpenNI/Include/OpenNI.h \
		../../OpenNI/Include/OniPlatform.h \
		../../OpenNI/Include/Win32/OniPlatformWin32.h \
		../../OpenNI/Include/Android-Arm/OniPlatformAndroid-Arm.h \
		../../OpenNI/Include/Linux-x86/OniPlatformLinux-x86.h \
		../../OpenNI/Include/Linux-Arm/OniPlatformLinux-Arm.h \
		../../OpenNI/Include/MacOSX/OniPlatformMacOSX.h \
		../../OpenNI/Include/OniProperties.h \
		../../OpenNI/Include/OniEnums.h \
		../../OpenNI/Include/OniCAPI.h \
		../../OpenNI/Include/OniCTypes.h \
		../../OpenNI/Include/OniCEnums.h \
		../../OpenNI/Include/OniCProperties.h \
		../../OpenNI/Include/OniVersion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewer_pcl.o viewer_pcl.cpp

viewer_save.o: viewer_save.cpp viewer.h \
		../../OpenNI/Include/OpenNI.h \
		../../OpenNI/Include/OniPlatform.h \
		../../OpenNI/Include/Win32/OniPlatformWin32.h \
		../../OpenNI/Include/Android-Arm/OniPlatformAndroid-Arm.h \
		../../OpenNI/Include/Linux-x86/OniPlatformLinux-x86.h \
		../../OpenNI/Include/Linux-Arm/OniPlatformLinux-Arm.h \
		../../OpenNI/Include/MacOSX/OniPlatformMacOSX.h \
		../../OpenNI/Include/OniProperties.h \
		../../OpenNI/Include/OniEnums.h \
		../../OpenNI/Include/OniCAPI.h \
		../../OpenNI/Include/OniCTypes.h \
		../../OpenNI/Include/OniCEnums.h \
		../../OpenNI/Include/OniCProperties.h \
		../../OpenNI/Include/OniVersion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewer_save.o viewer_save.cpp

sliders.o: sliders.cpp sliders.h \
		ui_sliders.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sliders.o sliders.cpp

moc_sliders.o: moc_sliders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sliders.o moc_sliders.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

